name = "transfer-sh-dl-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-02"
routes = ["transfer.uuid.rocks/*","transfer2.uuid.rocks/*","upload.geostyx.com/*","transfer.geostyx.com/*","archive.uuid.rocks/*"]
node_compat = true
logpush = true

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'transfer-sh'

[[r2_buckets]]
binding = 'BUCKET_GEO'
bucket_name = 'transfer-geostyx-com'

[[r2_buckets]]
binding = 'BUCKET_ARCHIVE'
bucket_name = 'archive-uuid-rocks'

[[ d1_databases ]]
binding = "DB"
database_name = "transfer-sh-fast"
database_id = "b53e399d-b9d7-4814-834d-a0e655d4409a"

[[queues.producers]]
  queue = "transfer-sh"
  binding = "QUEUE"

[[queues.consumers]]
  queue = "transfer-sh"
  max_batch_size = 100   # Max messages per batch
  max_batch_timeout = 1  # Max seconds to wait before batch is full
  max_retries = 3       # Max retries per batch
  max_concurrency = 1
